dataChamp = {
    "Aatrox": {
        " In the Jungle (9%)Aatrox In the Jungle Counters: 3,2792,2428041932713 matches, 35 counter championsHide  Jungle": {
            "ALL": {
                "Popular": {
                    "Diana": 171,
                    "Ekko": 63,
                    "Elise": 51,
                    "Evelynn": 100,
                    "Fiddlesticks": 76,
                    "Graves": 141,
                    "Hecarim": 60,
                    "Ivern": 48,
                    "Jarvan iv": 41,
                    "Karthus": 49,
                    "Kayn": 211,
                    "Khazix": 190,
                    "Kindred": 56,
                    "Lee sin": 209,
                    "Lillia": 52,
                    "Master yi": 78,
                    "Nidalee": 53,
                    "Nocturne": 108,
                    "Nunu willump": 62,
                    "Olaf": 37,
                    "Poppy": 45,
                    "Rammus": 50,
                    "Reksai": 41,
                    "Rengar": 58,
                    "Sejuani": 39,
                    "Shaco": 78,
                    "Shyvana": 52,
                    "Trundle": 52,
                    "Udyr": 32,
                    "Vi": 53,
                    "Viego": 206,
                    "Volibear": 70,
                    "Warwick": 46,
                    "Xin zhao": 156,
                    "Zac": 102,
                }
            },
            "CHALLENGER": {"Popular": {}},
            "DIAMOND": {
                "Popular": {
                    "Diana": 47,
                    "Fiddlesticks": 25,
                    "Graves": 50,
                    "Kayn": 38,
                    "Khazix": 38,
                    "Lee sin": 62,
                    "Nocturne": 25,
                    "Viego": 52,
                    "Xin zhao": 28,
                    "Zac": 37,
                }
            },
            "MASTER": {"Popular": {}},
            "PLATINUM": {
                "Popular": {
                    "Diana": 110,
                    "Ekko": 45,
                    "Elise": 34,
                    "Evelynn": 75,
                    "Fiddlesticks": 46,
                    "Graves": 77,
                    "Hecarim": 45,
                    "Kayn": 163,
                    "Khazix": 141,
                    "Kindred": 40,
                    "Lee sin": 123,
                    "Lillia": 30,
                    "Master yi": 62,
                    "Nidalee": 33,
                    "Nocturne": 76,
                    "Nunu willump": 31,
                    "Olaf": 28,
                    "Poppy": 31,
                    "Rammus": 40,
                    "Rengar": 43,
                    "Sejuani": 30,
                    "Shaco": 52,
                    "Shyvana": 43,
                    "Trundle": 41,
                    "Vi": 43,
                    "Viego": 131,
                    "Volibear": 50,
                    "Warwick": 41,
                    "Xin zhao": 115,
                    "Zac": 63,
                }
            },
        },
        " Top Lane (86%)Aatrox Top Lane Counters: 31,43720,4878,3082,196326120 matches, 55 counter championsHide Top Lane": {
            "ALL": {
                "Popular": {
                    "Akali": 263,
                    "Akshan": 148,
                    "Camille": 1800,
                    "Cassiopeia": 157,
                    "Chogath": 314,
                    "Darius": 849,
                    "Dr mundo": 1100,
                    "Fiora": 1200,
                    "Gangplank": 640,
                    "Garen": 891,
                    "Gnar": 520,
                    "Gragas": 159,
                    "Graves": 262,
                    "Gwen": 625,
                    "Heimerdinger": 100,
                    "Illaoi": 345,
                    "Irelia": 1200,
                    "Jax": 935,
                    "Jayce": 535,
                    "Kayle": 700,
                    "Kennen": 448,
                    "Kled": 428,
                    "Lee sin": 219,
                    "Lillia": 109,
                    "Malphite": 578,
                    "Mordekaiser": 839,
                    "Nasus": 653,
                    "Ornn": 470,
                    "Pantheon": 166,
                    "Poppy": 183,
                    "Quinn": 211,
                    "Renekton": 698,
                    "Rengar": 227,
                    "Riven": 1200,
                    "Ryze": 124,
                    "Sett": 2000,
                    "Shen": 905,
                    "Singed": 299,
                    "Sion": 645,
                    "Sylas": 269,
                    "Tahm kench": 1300,
                    "Teemo": 518,
                    "Trundle": 329,
                    "Tryndamere": 503,
                    "Urgot": 627,
                    "Vayne": 156,
                    "Viego": 249,
                    "Vladimir": 173,
                    "Volibear": 456,
                    "Warwick": 191,
                    "Wukong": 787,
                    "Yasuo": 253,
                    "Yone": 391,
                    "Yorick": 342,
                }
            },
            "CHALLENGER": {"Popular": {}},
            "DIAMOND": {
                "Popular": {
                    "Akali": 66,
                    "Akshan": 26,
                    "Camille": 558,
                    "Cassiopeia": 45,
                    "Chogath": 91,
                    "Darius": 187,
                    "Dr mundo": 283,
                    "Fiora": 320,
                    "Gangplank": 167,
                    "Garen": 166,
                    "Gnar": 124,
                    "Gragas": 54,
                    "Graves": 73,
                    "Gwen": 164,
                    "Heimerdinger": 27,
                    "Illaoi": 88,
                    "Irelia": 310,
                    "Jax": 204,
                    "Jayce": 157,
                    "Kayle": 180,
                    "Kennen": 121,
                    "Kled": 143,
                    "Lee sin": 58,
                    "Lucian": 29,
                    "Malphite": 148,
                    "Mordekaiser": 209,
                    "Nasus": 144,
                    "Ornn": 149,
                    "Pantheon": 42,
                    "Poppy": 49,
                    "Quinn": 48,
                    "Renekton": 188,
                    "Rengar": 76,
                    "Riven": 385,
                    "Ryze": 28,
                    "Sett": 568,
                    "Shen": 265,
                    "Singed": 75,
                    "Sion": 154,
                    "Sylas": 97,
                    "Tahm kench": 343,
                    "Teemo": 121,
                    "Trundle": 99,
                    "Tryndamere": 133,
                    "Urgot": 144,
                    "Vayne": 48,
                    "Viego": 67,
                    "Vladimir": 44,
                    "Volibear": 116,
                    "Warwick": 52,
                    "Wukong": 224,
                    "Yasuo": 60,
                    "Yone": 104,
                    "Yorick": 67,
                }
            },
            "MASTER": {
                "Popular": {
                    "Camille": 175,
                    "Darius": 57,
                    "Dr mundo": 84,
                    "Fiora": 130,
                    "Gangplank": 42,
                    "Garen": 28,
                    "Gnar": 36,
                    "Gwen": 53,
                    "Irelia": 69,
                    "Jax": 44,
                    "Jayce": 69,
                    "Kayle": 33,
                    "Kennen": 38,
                    "Kled": 42,
                    "Lee sin": 38,
                    "Malphite": 37,
                    "Mordekaiser": 35,
                    "Ornn": 33,
                    "Poppy": 34,
                    "Renekton": 60,
                    "Rengar": 25,
                    "Riven": 88,
                    "Sett": 147,
                    "Shen": 51,
                    "Sion": 44,
                    "Tahm kench": 101,
                    "Urgot": 29,
                    "Volibear": 29,
                    "Wukong": 47,
                    "Yone": 28,
                }
            },
            "PLATINUM": {
                "Popular": {
                    "Akali": 183,
                    "Akshan": 102,
                    "Camille": 1100,
                    "Cassiopeia": 91,
                    "Chogath": 216,
                    "Darius": 600,
                    "Dr mundo": 700,
                    "Fiora": 730,
                    "Gangplank": 426,
                    "Garen": 694,
                    "Gnar": 346,
                    "Gragas": 76,
                    "Graves": 160,
                    "Gwen": 399,
                    "Heimerdinger": 67,
                    "Illaoi": 244,
                    "Irelia": 842,
                    "Jax": 669,
                    "Jayce": 291,
                    "Kayle": 486,
                    "Kennen": 273,
                    "Kled": 239,
                    "Lee sin": 114,
                    "Lillia": 73,
                    "Malphite": 381,
                    "Mordekaiser": 590,
                    "Nasus": 490,
                    "Ornn": 276,
                    "Pantheon": 112,
                    "Poppy": 96,
                    "Quinn": 149,
                    "Renekton": 436,
                    "Rengar": 122,
                    "Riven": 758,
                    "Ryze": 85,
                    "Sett": 1300,
                    "Shen": 573,
                    "Singed": 214,
                    "Sion": 440,
                    "Sylas": 147,
                    "Tahm kench": 874,
                    "Teemo": 371,
                    "Trundle": 212,
                    "Tryndamere": 347,
                    "Urgot": 448,
                    "Vayne": 94,
                    "Viego": 154,
                    "Vladimir": 118,
                    "Volibear": 306,
                    "Warwick": 126,
                    "Wukong": 514,
                    "Yasuo": 176,
                    "Yone": 252,
                    "Yorick": 262,
                }
            },
        },
    }
}
